require("dotenv").config();

const {
  PORT,
  IMAGEKIT_PUBLIC_KEY,
  IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_URL_ENDPOINT,
} = process.env;

const ENV = {
  PORT: PORT,
  IMAGEKIT_PUBLIC_KEY: IMAGEKIT_PUBLIC_KEY,
  IMAGEKIT_PRIVATE_KEY: IMAGEKIT_PRIVATE_KEY,
  IMAGEKIT_URL_ENDPOINT: IMAGEKIT_URL_ENDPOINT,
};

module.exports = ENV;
